2023-02-08 14:21:03,793:INFO:Initializing load_model()
2023-02-08 14:21:03,799:INFO:load_model(model_name=final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:22:06,408:INFO:Initializing load_model()
2023-02-08 14:22:06,433:INFO:load_model(model_name=final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:22:06,537:INFO:Initializing predict_model()
2023-02-08 14:22:06,552:INFO:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(ml_usecase='classification',
                                      target='Diagnosis')),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='mean',
                                target_variable=None)),
                ('new_levels1',
                 New_Catagorical_Levels_in_TestData(replacement_strategy='least '
                                                                         'frequent',
                                                    t...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Diagnosis')),
                ('fix_perfect', Remove_100(target='Diagnosis')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model', 'final_gbc']]), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:22:06,556:INFO:Checking exceptions
2023-02-08 14:22:06,560:INFO:Preloading libraries
2023-02-08 14:22:06,561:ERROR:Pipeline not found. Exception:
2023-02-08 14:22:06,599:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 14:22:29,478:INFO:Initializing load_model()
2023-02-08 14:22:29,479:INFO:load_model(model_name=final_gbc20230204.pkl, platform=None, authentication=None, verbose=True)
2023-02-08 14:22:39,989:INFO:Initializing load_model()
2023-02-08 14:22:40,003:INFO:load_model(model_name=final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:22:40,049:INFO:Initializing predict_model()
2023-02-08 14:22:40,052:INFO:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(ml_usecase='classification',
                                      target='Diagnosis')),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='mean',
                                target_variable=None)),
                ('new_levels1',
                 New_Catagorical_Levels_in_TestData(replacement_strategy='least '
                                                                         'frequent',
                                                    t...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Diagnosis')),
                ('fix_perfect', Remove_100(target='Diagnosis')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model', 'final_gbc']]), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:22:40,057:INFO:Checking exceptions
2023-02-08 14:22:40,058:INFO:Preloading libraries
2023-02-08 14:22:40,058:ERROR:Pipeline not found. Exception:
2023-02-08 14:22:40,059:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 14:23:52,144:INFO:Initializing load_model()
2023-02-08 14:23:52,145:INFO:load_model(model_name=final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:25:32,118:INFO:Initializing load_model()
2023-02-08 14:25:32,119:INFO:load_model(model_name=final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:25:32,197:INFO:Initializing predict_model()
2023-02-08 14:25:32,198:INFO:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(ml_usecase='classification',
                                      target='Diagnosis')),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='mean',
                                target_variable=None)),
                ('new_levels1',
                 New_Catagorical_Levels_in_TestData(replacement_strategy='least '
                                                                         'frequent',
                                                    t...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Diagnosis')),
                ('fix_perfect', Remove_100(target='Diagnosis')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model', 'final_gbc']]), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:25:32,203:INFO:Checking exceptions
2023-02-08 14:25:32,207:INFO:Preloading libraries
2023-02-08 14:25:32,208:ERROR:Pipeline not found. Exception:
2023-02-08 14:25:32,209:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 14:28:22,297:INFO:Initializing load_model()
2023-02-08 14:28:22,298:INFO:load_model(model_name=final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:28:22,379:INFO:Initializing predict_model()
2023-02-08 14:28:22,383:INFO:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(ml_usecase='classification',
                                      target='Diagnosis')),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='mean',
                                target_variable=None)),
                ('new_levels1',
                 New_Catagorical_Levels_in_TestData(replacement_strategy='least '
                                                                         'frequent',
                                                    t...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Diagnosis')),
                ('fix_perfect', Remove_100(target='Diagnosis')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model', 'final_gbc']]), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:28:22,388:INFO:Checking exceptions
2023-02-08 14:28:22,394:INFO:Preloading libraries
2023-02-08 14:28:22,396:ERROR:Pipeline not found. Exception:
2023-02-08 14:28:22,396:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 14:29:45,941:INFO:Initializing load_model()
2023-02-08 14:29:45,942:INFO:load_model(model_name=final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:30:00,671:INFO:Initializing load_model()
2023-02-08 14:30:00,672:INFO:load_model(model_name=final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:32:18,559:INFO:Initializing load_model()
2023-02-08 14:32:18,560:INFO:load_model(model_name=./final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:32:18,607:INFO:Initializing predict_model()
2023-02-08 14:32:18,608:INFO:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(ml_usecase='classification',
                                      target='Diagnosis')),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='mean',
                                target_variable=None)),
                ('new_levels1',
                 New_Catagorical_Levels_in_TestData(replacement_strategy='least '
                                                                         'frequent',
                                                    t...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Diagnosis')),
                ('fix_perfect', Remove_100(target='Diagnosis')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model', 'final_gbc']]), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:32:18,612:INFO:Checking exceptions
2023-02-08 14:32:18,614:INFO:Preloading libraries
2023-02-08 14:32:18,616:ERROR:Pipeline not found. Exception:
2023-02-08 14:32:18,618:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 14:37:34,864:INFO:Initializing load_model()
2023-02-08 14:37:34,886:INFO:load_model(model_name=./final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:37:34,966:INFO:Initializing predict_model()
2023-02-08 14:37:34,969:INFO:predict_model(estimator=DataTypes_Auto_infer(ml_usecase='classification', target='Diagnosis'), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:37:34,970:INFO:Checking exceptions
2023-02-08 14:37:34,971:INFO:Preloading libraries
2023-02-08 14:37:34,971:ERROR:Pipeline not found. Exception:
2023-02-08 14:37:34,972:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 14:37:44,903:INFO:Initializing load_model()
2023-02-08 14:37:44,904:INFO:load_model(model_name=./final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:37:44,937:INFO:Initializing predict_model()
2023-02-08 14:37:44,937:INFO:predict_model(estimator=Simple_Imputer(categorical_strategy='not_available',
               fill_value_categorical=None, fill_value_numerical=None,
               numeric_strategy='mean', target_variable=None), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:37:44,940:INFO:Checking exceptions
2023-02-08 14:37:44,940:INFO:Preloading libraries
2023-02-08 14:37:44,941:ERROR:Pipeline not found. Exception:
2023-02-08 14:37:44,942:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 14:38:01,256:INFO:Initializing load_model()
2023-02-08 14:38:01,257:INFO:load_model(model_name=./final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:38:01,306:INFO:Initializing predict_model()
2023-02-08 14:38:01,307:INFO:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(ml_usecase='classification',
                                      target='Diagnosis')),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='mean',
                                target_variable=None)),
                ('new_levels1',
                 New_Catagorical_Levels_in_TestData(replacement_strategy='least '
                                                                         'frequent',
                                                    t...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Diagnosis')),
                ('fix_perfect', Remove_100(target='Diagnosis')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model', 'final_gbc']]), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:38:01,313:INFO:Checking exceptions
2023-02-08 14:45:12,877:INFO:Initializing load_model()
2023-02-08 14:45:12,877:INFO:load_model(model_name=./final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:45:12,920:INFO:Initializing predict_model()
2023-02-08 14:45:12,922:INFO:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(ml_usecase='classification',
                                      target='Diagnosis')),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='mean',
                                target_variable=None)),
                ('new_levels1',
                 New_Catagorical_Levels_in_TestData(replacement_strategy='least '
                                                                         'frequent',
                                                    t...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Diagnosis')),
                ('fix_perfect', Remove_100(target='Diagnosis')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model', 'final_gbc']]), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:45:12,926:INFO:Checking exceptions
2023-02-08 14:45:29,696:INFO:Initializing load_model()
2023-02-08 14:45:29,696:INFO:load_model(model_name=./final_gbc20230204, platform=None, authentication=None, verbose=True)
2023-02-08 14:45:29,738:INFO:Initializing predict_model()
2023-02-08 14:45:29,739:INFO:predict_model(estimator=Pipeline(steps=[('dtypes',
                 DataTypes_Auto_infer(ml_usecase='classification',
                                      target='Diagnosis')),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_strategy='mean',
                                target_variable=None)),
                ('new_levels1',
                 New_Catagorical_Levels_in_TestData(replacement_strategy='least '
                                                                         'frequent',
                                                    t...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='Diagnosis')),
                ('fix_perfect', Remove_100(target='Diagnosis')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough'),
                ['trained_model', 'final_gbc']]), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 14:45:29,742:INFO:Checking exceptions
2023-02-08 14:45:29,743:INFO:Preloading libraries
2023-02-08 14:45:29,744:ERROR:Pipeline not found. Exception:
2023-02-08 14:45:29,747:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 16:23:46,485:INFO:Initializing predict_model()
2023-02-08 16:23:46,486:INFO:predict_model(estimator=GradientBoostingClassifier(random_state=0), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 16:23:46,486:INFO:Checking exceptions
2023-02-08 16:23:46,487:INFO:Preloading libraries
2023-02-08 16:23:46,487:ERROR:Pipeline not found. Exception:
2023-02-08 16:23:46,490:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 16:25:43,166:INFO:Initializing predict_model()
2023-02-08 16:25:43,167:INFO:predict_model(estimator=GradientBoostingClassifier(random_state=0), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 16:25:43,168:INFO:Checking exceptions
2023-02-08 16:25:43,169:INFO:Preloading libraries
2023-02-08 16:25:43,170:ERROR:Pipeline not found. Exception:
2023-02-08 16:25:43,172:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 16:27:42,416:INFO:Initializing predict_model()
2023-02-08 16:27:42,416:INFO:predict_model(estimator=GradientBoostingClassifier(random_state=0), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 16:27:42,417:INFO:Checking exceptions
2023-02-08 16:27:42,418:INFO:Preloading libraries
2023-02-08 16:27:42,418:ERROR:Pipeline not found. Exception:
2023-02-08 16:27:42,421:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 16:30:11,002:INFO:Initializing predict_model()
2023-02-08 16:30:11,003:INFO:predict_model(estimator=GradientBoostingClassifier(random_state=0), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 16:30:11,004:INFO:Checking exceptions
2023-02-08 16:30:11,006:INFO:Preloading libraries
2023-02-08 16:30:11,006:ERROR:Pipeline not found. Exception:
2023-02-08 16:30:11,008:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 16:38:06,455:INFO:Initializing predict_model()
2023-02-08 16:38:06,455:INFO:predict_model(estimator=GradientBoostingClassifier(random_state=0), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 16:38:06,460:INFO:Checking exceptions
2023-02-08 16:38:06,461:INFO:Preloading libraries
2023-02-08 16:38:06,461:ERROR:Pipeline not found. Exception:
2023-02-08 16:38:06,462:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 16:52:51,111:INFO:Initializing predict_model()
2023-02-08 16:52:51,111:INFO:predict_model(estimator=GradientBoostingClassifier(random_state=0), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 16:52:51,113:INFO:Checking exceptions
2023-02-08 16:52:51,113:INFO:Preloading libraries
2023-02-08 16:52:51,115:ERROR:Pipeline not found. Exception:
2023-02-08 16:52:51,116:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

2023-02-08 17:08:37,336:INFO:Initializing predict_model()
2023-02-08 17:08:37,337:INFO:predict_model(estimator=GradientBoostingClassifier(random_state=0), probability_threshold=None, encoded_labels=False, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.CLASSIFICATION, display=None, drift_kwargs=None)
2023-02-08 17:08:37,340:INFO:Checking exceptions
2023-02-08 17:08:37,341:INFO:Preloading libraries
2023-02-08 17:08:37,341:ERROR:Pipeline not found. Exception:
2023-02-08 17:08:37,346:ERROR:Traceback (most recent call last):
  File "D:\monshin\lib\site-packages\pycaret\internal\tabular.py", line 9044, in predict_model
    dtypes = prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined

